/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum FilterType {
    USER_OS = 'userOs',
    USER_BROWSER = 'userBrowser',
    USER_DEVICE = 'userDevice',
    USER_COUNTRY = 'userCountry',
    USER_CITY = 'userCity',
    USER_STATE = 'userState',
    USER_ID = 'userId',
    USER_ANONYMOUS_ID = 'userAnonymousId',
    REFERRER = 'referrer',
    REV_ID = 'revId',
    USER_OS_IOS = 'userOsIos',
    USER_DEVICE_IOS = 'userDeviceIos',
    USER_COUNTRY_IOS = 'userCountryIos',
    USER_ID_IOS = 'userIdIos',
    USER_ANONYMOUS_ID_IOS = 'userAnonymousIdIos',
    REV_ID_IOS = 'revIdIos',
    DURATION = 'duration',
    PLATFORM = 'platform',
    METADATA = 'metadata',
    ISSUE = 'issue',
    EVENTS_COUNT = 'eventsCount',
    UTM_SOURCE = 'utmSource',
    UTM_MEDIUM = 'utmMedium',
    UTM_CAMPAIGN = 'utmCampaign',
    THERMAL_STATE = 'thermalState',
    MAIN_THREAD_CPU = 'mainThreadCPU',
    VIEW_COMPONENT = 'viewComponent',
    LOG_EVENT = 'logEvent',
    CLICK_EVENT = 'clickEvent',
    MEMORY_USAGE = 'memoryUsage',
}
